### ISSUE TITLE
Exoplayer can't seek m3u8 both stream and local file.

### ISSUE THREAD

**Issue by aungpyaesone** [yoobi/exoplayer-kotlin#13]
I'm using exo-download in this repo. Could you help?

**Comment by yoobi** [comment]
Hello, can you give me more details about your issue?

**Comment by aungpyaesone** [comment]
Here is my local file.
https://drive.google.com/file/d/1sMP83o_-csp6H7Xa_MMJFfxTQB-tjiTb/view?usp=sharing

I can play this file but can't seek to other position on exo-player. could you help?

**Comment by yoobi** [comment]
Have you tried with url such as the one in this [website](https://ottverse.com/free-hls-m3u8-test-urls/) ? It might be your file which doesn't allow seeking.
Also I can't really help you if you do not show some code

**Comment by aungpyaesone** [comment]
Here is url 

https://vod.ddzykan.com:2345/2023-07-15/6d00529c-ad28-7d09-d381-2c14afce967b/f326eab244e1_h264_1734K/b03c6a7a-e483-51c6-408e-00c8159e6e64/index.m3u8?md5=IoayRTLP-Frht6idwwUnUg&expires=1718459149

**Comment by yoobi** [comment]
It looks like there is an error in your file. Not much I can do here
