### ISSUE TITLE
Question : Will this code support h265 file format

### ISSUE THREAD

**Issue by purvagevaria** [yoobi/exoplayer-kotlin#2]
I want to load file with h265 extention will this code support h265 file ?

**Comment by yoobi** [comment]
I haven't tried but from what I've found in exoplayer doc https://exoplayer.dev/supported-formats.html and in this issue https://github.com/google/ExoPlayer/issues/5659 h.265 should be supported

**Comment by purvagevaria** [comment]
@yoobi Thanks for your reply but unfortunately I tried different examples but h265 support is not there. Closing this issue I got the answer .
