### ISSUE TITLE
issue running certain modules ..!!!

### ISSUE THREAD

**Issue by vivekpanchal** [yoobi/exoplayer-kotlin#3]
hey,
I am having an issue while trying to run the fullscreen dialog, fullscreen layout parms modules can you please check ..!!
I am getting null pointer issues 

```
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at io.github.yoobi.fullscreendialog.MainActivity.J(:132)
        at io.github.yoobi.fullscreendialog.MainActivity.onCreate(:49)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)`
```

**Comment by yoobi** [comment]
Thank you for reporting this, I'll look into it :)

**Comment by yoobi** [comment]
It is fixed, can you pull and confirm ?

**Comment by vivekpanchal** [comment]
well, all the modules working now but for fullscreen when we exit it should have returned to the original portrait state right?

**Comment by yoobi** [comment]
No, it's in the `requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_SENSOR` if you want portrait you can change this line

**Comment by vivekpanchal** [comment]
cool everything is working then 👍
