### ISSUE TITLE
You should add screenshots.

### ISSUE THREAD

**Issue by halilozel1903** [yoobi/exoplayer-kotlin#5]
How you doin’ 

I think you should add screenshots in ReadMe.

Fyi @yoobi .

Thanks.

**Comment by halilozel1903** [comment]
Hi, Will you add readme file? @yoobi

**Comment by yoobi** [comment]
Hello,

There is already a readme file, I'll add the gifs of the different feature when I got the time, you can also make a PR for that and I'll merge it

**Comment by halilozel1903** [comment]
Okie, sure.

**Comment by yoobi** [comment]
Closing because #6 is now closed
