### ISSUE TITLE
can you help me regarding using your code in java

### ISSUE THREAD

**Issue by ThreeMinutesFix** [yoobi/exoplayer-kotlin#7]
i have app developed in java but i want to use your quality dialog feature 
```
   if (contentLoaded) {
                MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
                if (mappedTrackInfo != null) {
                    CharSequence title = "Video";
                    int rendererIndex = 0;
                    int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
                    boolean allowAdaptiveSelections =
                            rendererType == C.TRACK_TYPE_VIDEO
                                    || (rendererType == C.TRACK_TYPE_AUDIO
                                    && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
                                    == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);

                    TrackSelectionDialog trackSelectionDialog =
                            TrackSelectionDialog.createForPlayer(
                                    simpleExoPlayer,
                                    /* onDismissListener= */ dismissedDialog -> isShowingTrackSelectionDialog = false);
                    trackSelectionDialog.show(getSupportFragmentManager(), /* tag= */ null);
```

this is my current implementation i want to do or change like yours only to show quality other two like audio and sub in different dialog

**Comment by yoobi** [comment]
Do you mean you want to create a 3 dialogs ? One for video, one for audio and one for sub ?

**Comment by ThreeMinutesFix** [comment]
exactly

**Comment by yoobi** [comment]
It already exists within the Exoplayer demo app. Clone https://github.com/google/ExoPlayer/tree/release-v2/demos/main and then run the demo app on your phone. You'll find everything that you need.

**Comment by ThreeMinutesFix** [comment]
ok i check it thankyou dear friend for your time :)

**Comment by ThreeMinutesFix** [comment]
hi,
i checked but that demo contain only styled exoplayer which has build in things but i want to use the simpleexoplayer. will you guide me on that

**Comment by yoobi** [comment]
[SimpleExoplayer](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html) is deprecated you really should follow what's on the demo as it's using the latest version on Exoplayer in Java.

**Comment by ThreeMinutesFix** [comment]
ok bro thankyou somuch for your time i will certainly check on it

**Comment by ThreeMinutesFix** [comment]
yes bro i useExoplayer as alternative for simple exoplayer but i dnt like styled exoplayer as it not support custom controller! but still thanks for your time in helping to solve my issue i will certainly look on it one more time

**Comment by yoobi** [comment]
You can definitely use custom controller on a StyledPlayerView with something like:
```
<com.google.android.exoplayer2.ui.StyledPlayerView
            app:controller_layout_id="@layout/custom_exo_player_controls"
            app:player_layout_id="@layout/custom_exo_player_layout"
/>
```
You can even change player_layout if you'd like

**Comment by yoobi** [comment]
Closing as no answer, feel free to re-open
