### ISSUE TITLE
Add samples for drm content also like for downloading it specfically 

### ISSUE THREAD

**Issue by jasi381** [yoobi/exoplayer-kotlin#9]
https://github.com/androidx/media/blob/release/demos/main/src/main/assets/media.exolist.json

it contains various drm file 
i tried downloading the drm file but it failed

**Comment by yoobi** [comment]
Hello,

I will be able to work on this only end of november. You can however check the official repo in the meantime https://github.com/google/ExoPlayer/tree/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo

**Comment by jasi381** [comment]
Oh,:( i need it urgently, but no worries

**Comment by yoobi** [comment]
The exoplayer demo I shared above is doing exactly what you need, you can check their code :)

**Comment by yoobi** [comment]
Hello, you can check the code in this [module](https://github.com/yoobi/exoplayer-kotlin/tree/master/drmdownloadvideo)
